### ISSUE TITLE
Unable to use the default value of quarkus.config.source.jdbc.url

### ISSUE THREAD

**Issue by nyko29** [quarkiverse/quarkus-config-extensions#149] opened 2023-07-07 15:27 UTC
I got a the following error if the value of quarkus.config.source.jdbc.url is not set in my applications.properties.
In the documentation it is stated that the default value of **quarkus.config.source.jdbc.url** is the value of **quarkus.datasource.jdbc.url**

But it seems to be not working. Indeed in my application.properties I have:

`
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/mydbname
`
When I launch my application I got the following error:

```2023-07-07 12:44:51,253 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Unable to get java.sql.Driver from DriverManager
	at io.agroal.pool.ConnectionFactory.newDriver(ConnectionFactory.java:130)
	at io.agroal.pool.ConnectionFactory.<init>(ConnectionFactory.java:69)
	at io.agroal.pool.ConnectionPool.<init>(ConnectionPool.java:108)
	at io.agroal.pool.DataSource.<init>(DataSource.java:37)
	at io.agroal.pool.DataSourceProvider.getDataSource(DataSourceProvider.java:21)
	at io.agroal.api.AgroalDataSource.from(AgroalDataSource.java:41)
	at io.quarkiverse.config.jdbc.runtime.Repository.prepareDataSource(Repository.java:107)
	at io.quarkiverse.config.jdbc.runtime.Repository.<init>(Repository.java:32)
	at io.quarkiverse.config.jdbc.runtime.JdbcConfigSourceFactory.getConfigSources(JdbcConfigSourceFactory.java:24)
	at io.quarkiverse.config.jdbc.runtime.JdbcConfigSourceFactory.getConfigSources(JdbcConfigSourceFactory.java:14)
	at io.smallrye.config.ConfigSourceFactory$ConfigurableConfigSourceFactory.getConfigSources(ConfigSourceFactory.java:52)
	at io.smallrye.config.ConfigurableConfigSource.getConfigSources(ConfigurableConfigSource.java:50)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.mapLateSources(SmallRyeConfig.java:669)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:553)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:69)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:623)
	at io.quarkus.runtime.generated.Config.<clinit>(Unknown Source)
	... 15 more
Caused by: java.sql.SQLException: No suitable driver
	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
	at io.agroal.pool.ConnectionFactory.newDriver(ConnectionFactory.java:128)
	... 31 more

2023-07-07 12:44:51,254 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
```

BUt if I put the two properties in application.properties then the application starts well:
```
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/mydbname
quarkus.config.source.jdbc.url=jdbc:postgresql://postgresql:5432/mydbname
```

Am I missing something ?

I am using quarkus 3.0.0 and quarkus-config-extensions 2.0.1

**Comment by radcortez** [comment] 2023-07-07 17:23
I'll have a look.

**Comment by radcortez** [comment] 2023-07-07 18:43
Hum... I've tried to reproduce it one of my projects, but it worked as expected. Are you able to provide a reproducer? Thanks!

**Comment by radcortez** [comment] 2023-10-24 18:34
Closing due to lack of information.

**Closed by radcortez** 2023-10-24 18:34 UTC
